//File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

//import 'firebase_options.dart';

// ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC87Y9DlT8UuMK1s3r2Wcl2ao83Nh8ACyE',
    appId: '1:1054441551330:web:942a3838b65a44be1675bb',
    messagingSenderId: '1054441551330',
    projectId: 'affinity-app-1018',
    authDomain: 'affinity-app-1018.firebaseapp.com',
    storageBucket: 'affinity-app-1018.appspot.com',
    measurementId: 'G-5ZC7T43Q7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-8Hg62gQ-weU1unj2cc2uEAgawaCrfYo',
    appId: '1:1054441551330:android:0ba8b38aa695f4541675bb',
    messagingSenderId: '1054441551330',
    projectId: 'affinity-app-1018',
    storageBucket: 'affinity-app-1018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgQdfxar9tR9s11_lD3ms-gFE6LhXM7_4',
    appId: '1:1054441551330:ios:4450b51f1113cca81675bb',
    messagingSenderId: '1054441551330',
    projectId: 'affinity-app-1018',
    storageBucket: 'affinity-app-1018.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgQdfxar9tR9s11_lD3ms-gFE6LhXM7_4',
    appId: '1:1054441551330:ios:4450b51f1113cca81675bb',
    messagingSenderId: '1054441551330',
    projectId: 'affinity-app-1018',
    storageBucket: 'affinity-app-1018.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );
}
